/*
 * Copyright 2026 The SuperPlayer Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.superplayer.realtime

import android.os.SystemClock
import androidx.media3.common.C
import androidx.media3.exoplayer.RenderersFactory
import androidx.media3.test.utils.FakeClock
import androidx.media3.test.utils.FakeRenderer
import androidx.media3.test.utils.robolectric.TestPlayerRunHelper
import androidx.test.core.app.ApplicationProvider
import com.superplayer.core.MediaRequest
import com.superplayer.core.SuperPlayer
import com.superplayer.core.TelemetryEvent
import com.superplayer.core.TelemetrySink
import com.superplayer.telemetry.QoeCollector
import com.superplayer.telemetry.SessionTraceRecorder
import com.superplayer.testkit.GoldenFile
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.Shadows.shadowOf
import org.robolectric.annotation.LooperMode
import java.util.Collections

/**
 * What a realtime session looks like as a session trace, pinned as a golden.
 *
 * The artifact is `SessionTraceRecorder`'s, and the reason for committing one here is ADR-0018
 * rule 6 and rule 8: the interesting content of this file is **what is absent**. A realtime session
 * opens no `DataSource`, so there is no `load` line and no `bandwidth` line anywhere in it, and a
 * reader comparing this trace against `superplayer-telemetry`'s HLS goldens can see the difference
 * rather than take the record's word for it. A future change that quietly put a realtime stream back
 * on the chain would show up here as lines appearing, which is exactly what a golden is for.
 *
 * What survives is equally the point: the state transitions are all there, so rebuffer and startup
 * metrics are derived from a realtime session exactly as from an HLS one (rule 8).
 *
 * **What this golden cannot show**, said rather than left to be inferred from a thin file: the
 * renderer is Media3's `FakeRenderer`, which decodes nothing and renders nothing, so the trace
 * carries no first-frame timing and its `tracks` line reads `video=none` — those are facts about the
 * fake, not about the realtime path. A rendition really being selected and a first frame really
 * arriving are a device's to show, which is #353.
 *
 * Regenerated by `./gradlew updateGoldenTraces` and by nothing else. `docs/testing.md`'s *Golden
 * traces* says what a diff means and what may go into one.
 */
@RunWith(RobolectricTestRunner::class)
@LooperMode(LooperMode.Mode.PAUSED)
class RealtimeGoldenTraceTest {

    @Test
    fun aRealtimeSessionFromSubscriptionToEnd() {
        GoldenFile.check("realtime-h264.trace", play())
    }

    private fun play(): String {
        val recorder = SessionTraceRecorder()
        // A sink of the test's own beside the recorder, because a golden has to be taken once the
        // delivery queue has drained, and `SessionEnded` is the event that says it has (ADR-0008
        // rule 4).
        val delivered = Collections.synchronizedList(mutableListOf<TelemetryEvent>())
        val player = SuperPlayer.Builder(ApplicationProvider.getApplicationContext())
            .setTelemetry(QoeCollector(TelemetrySink.composite(recorder, TelemetrySink { delivered += it })))
            .setRealtime(Realtime.transport(SCHEME) { ScriptedFrameSource(frames = FRAMES) })
            .setEngineConfigurator { configuration ->
                configuration.engine
                    .setClock(FakeClock(SystemClock.elapsedRealtime(), /* isAutoAdvancing = */ true))
                    .setRenderersFactory(
                        RenderersFactory { _, _, _, _, _ -> arrayOf(FakeRenderer(C.TRACK_TYPE_VIDEO)) },
                    )
            }
            .build()

        recorder.attach(player)
        player.setMediaRequest(MediaRequest.Builder(CONTENT).addSource("$SCHEME://relay.test/$CONTENT").build())
        player.prepare()
        // Played to a position and then released, because **a realtime session does not end on its
        // own**: ExoPlayer declares a period final from the timeline, and a live dynamic period of
        // unknown duration never is, so `STATE_ENDED` is unreachable here by construction rather
        // than by anything this module chose. A live session ends when the viewer leaves, and that
        // is what `release()` is. `RealtimeMediaPeriod.getBufferedPositionUs` carries the same note
        // where the behaviour is.
        TestPlayerRunHelper.playUntilPosition(player.exoPlayer, /* mediaItemIndex = */ 0, PLAY_TO_MS)
        player.release()
        runMainLooperUntilSessionEnded(delivered)
        return recorder.trace().format()
    }

    private fun runMainLooperUntilSessionEnded(delivered: List<TelemetryEvent>) {
        val looper = shadowOf(ApplicationProvider.getApplicationContext<android.content.Context>().mainLooper)
        repeat(LOOPER_TURNS) {
            if (synchronized(delivered) { delivered.any { event -> event is TelemetryEvent.SessionEnded } }) return
            looper.idle()
            Thread.sleep(1)
        }
        error("The session did not end within $LOOPER_TURNS turns of the main looper.")
    }

    private companion object {
        const val SCHEME = "superplayer-test-realtime"
        const val CONTENT = "studio-a"

        /** Ten seconds at 30 fps: comfortably more than [PLAY_TO_MS], so the edge is never reached. */
        const val FRAMES = 300

        /** Far enough in that startup is over and the trace has something to say; short enough to read. */
        const val PLAY_TO_MS = 2_000L

        /** A bound on the wait rather than on the session; `docs/testing.md` argues bounding the wait. */
        const val LOOPER_TURNS = 2_000
    }
}
